<a href="https://colab.research.google.com/github/abdul-coder/crypto/blob/master/Welcome_To_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
distance = [40, 50, 35]
speed = [5, 10, 7]

time = distance/speed
print(time)

TypeError: ignored

In [4]:
import numpy as np
distance = np.array(distance)
speed = np.array(speed)
print(distance)
print(speed)
time = distance/speed
print(time)

[40 50 35]
[ 5 10  7]
[8. 5. 5.]


In [7]:
a= [1, 2, 3, 4, 5]
b=[5, 6, 7, 8, 9]
c= a+b
print(c)

[1, 2, 3, 4, 5, 5, 6, 7, 8, 9]


In [17]:
a = np.array((1, 2, 3, 4))
b = np.array((5, 6, 7, 8))
c=a+b
print(c)
print(a**2)
print(b**2)

[ 6  8 10 12]
[ 1  4  9 16]
[25 36 49 64]


In [19]:
c = np.arange(10)
print(c)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
e = np.arange(5, 56, 5)
print(e)

[ 5 10 15 20 25 30 35 40 45 50 55]


In [34]:
h = np.linspace(1, 10, 30)
print(h)

[ 1.          1.31034483  1.62068966  1.93103448  2.24137931  2.55172414
  2.86206897  3.17241379  3.48275862  3.79310345  4.10344828  4.4137931
  4.72413793  5.03448276  5.34482759  5.65517241  5.96551724  6.27586207
  6.5862069   6.89655172  7.20689655  7.51724138  7.82758621  8.13793103
  8.44827586  8.75862069  9.06896552  9.37931034  9.68965517 10.        ]


In [40]:
data = np.array((1, 2, 3, 4, 5, 6, 7, 8, 9 , 10, 11, 12, 13, 14, 15, 16 , 17 , 18 , 19 , 20 , 21, 22, 32, 43))
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 32, 43])

In [42]:
data = data.reshape(8, 3)
data

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 32, 43]])

In [49]:
even_data = (data % 2==0)
even_data

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False],
       [ True, False,  True],
       [False,  True, False],
       [ True, False,  True],
       [False,  True, False],
       [ True,  True, False]])

In [56]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])